//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationForAll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrolment
    {
        public int EnrolmentId { get; set; }
        public System.DateTime StudentCourseStartDate { get; set; }
        public int PercentageCourseCompleted { get; set; }
        public string CourseDurationLeft { get; set; }
        public int CoursesCourseId { get; set; }
        public int StudentStudentId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
